#!/bin/bash

mkdir ~/apps

cd ~/apps

wget https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz

tar -xvzf nvim-linux64.tar.gz

tar -xvzf community_images.tar.gz

echo 'alias nvim="~/apps/nvim-linux64/bin/nvim"' >> ~/.bashrc

apt install ripgrep
