#!/bin/bash

mkdir ~/apps/bin -p

wget -O ~/apps/go.tar.gz https://go.dev/dl/go1.22.5.linux-amd64.tar.gz
tar -xzf ~/apps/go.tar.gz -C ~/apps/
rm ~/apps/go.tar.gz

ln -s ~/apps/go/bin/go ~/apps/bin/go
ln -s ~/apps/go/bin/gofmt ~/apps/bin/gofmt
